
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-permissions/scripts/setup.rb'
# 设置最低支持的 iOS 版本
platform :ios, min_ios_version_supported # 你可以根据需要调整最低版本

# 准备 React Native 项目
prepare_react_native_project!

# 根据环境变量决定是否使用框架链接
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AwesomeProject' do
  # 获取 React Native 配置
  config = use_native_modules!

  # 使用 React Native 相关的 Pod
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true  # 确保 Hermes 引擎启用
  )


  # 测试目标
  target 'AwesomeProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # 安装后处理
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # :ccache_enabled => true
    )
  end
end